version: "3.9"
services:
  api:
    build: ./status-state-api/
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  controller:
    build: ./status-state-controller/
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - api
  