version: "3.9"
services:
  api:
    build: ./status-state-api/
    ports:
      - "${PORT_API}:${PORT_API}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PORT_API=${PORT_API}
  controller:
    build: ./status-state-controller/
    ports:
      - "${PORT_CONTROLLER}:${PORT_CONTROLLER}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONUNBUFFERED=1
      - PORT_API=${PORT_API}
      - PORT_CONTROLLER=${PORT_CONTROLLER}
    depends_on:
      - api
  