version: "3"
services:
  api:
    build: ./status-state-api/
    ports:
      - "${PORT_API}:${PORT_API}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PORT_API=${PORT_API}
    extra_hosts:
      # creating extra role for Linux users
      - "host.docker.internal:host-gateway"
  controller:
    build: ./status-state-controller/
    ports:
      - "${PORT_CONTROLLER}:${PORT_CONTROLLER}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONUNBUFFERED=1
      - PORT_API=${PORT_API}
      - PORT_CONTROLLER=${PORT_CONTROLLER}
    depends_on:
      - api
    extra_hosts:
      - "host.docker.internal:host-gateway" 
  mock-container:
    image: nginx
    volumes:
    - ./templates:/etc/nginx/templates
    ports:
    - "80:${PORT_MOCK}"